spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.security.user.name=${SECURITYUSERNAME}
spring.security.user.password=${SECURITYPASSWORD}

#Copy these into application-test.properties for testing, remove before commiting
#Token.value is redundant since we are not using S3 Sessions


Thumbnail.Token.value=${TOKENVALUE}

Thumbnail.Access.Key.ID=${ACCESSKEYID}

Thumbnail.Secret.Access.Key=${SECRETACCESSKEY}

Thumbnail.Bucket.Name=${THUMBNAILBUCKETNAME}

First.Bucket.Name=${FIRSTBUCKETNAME}

Thumbnail.Height=${THUMBNAILHEIGHT}

Thumbnail.Width=${THUMBNAILWIDTH}

R2.URI=${R2URI}

kafka.topic=${KAFKATOPIC}

kafka.port=${KAFKAPORT}



server.port=${PORT:8082}

#actuator endpoints for prometheus
management.endpoints.web.exposure.include=prometheus
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}