spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.security.user.name=${SECURITYUSERNAME}
spring.security.user.password=${SECURITYPASSWORD}

#Copy these into application-test.properties for testing, remove before commiting
#Token.value is redundant since we are not using S3 Sessions
Token.value=${TOKENVALUE}

Access.Key.ID=${ACCESSKEYID}

Secret.Access.Key=${SECRETACCESSKEY}

Thumbnail.Token.value=${TOKENVALUE}

Thumbnail.Access.Key.ID=${ACCESSKEYID}

Thumbnail.Secret.Access.Key=${SECRETACCESSKEY}

Thumbnail.Bucket.Name=${THUMBNAILBUCKETNAME}

First.Token.value=${FIRSTTOKENVALUE}

First.Access.Key.ID=${FIRSTACCESSKEYID}

First.Secret.Access.Key=${FIRSTSECRETACCESSKEY}

First.Bucket.Name=${FIRSTBUCKETNAME}

R2.URI=${R2URI}


server.port=${PORT:8082}